// SPDX-License-Identifier: MIT
pragma solidity 0.8.10;

import "../../token/presets/IMSpaceMissionToken.sol";

contract Mission1ComponentPayload is IMSpaceMissionToken {

    /**
     * @dev Grants `DEFAULT_ADMIN_ROLE`, `MINTER_ROLE` and `PAUSER_ROLE` to the
     * account that deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    constructor(
        string memory name,
        string memory symbol,
        uint256 maxSupply,
        uint256 revealTimestamp
    ) IMSpaceMissionToken(name, symbol, maxSupply, revealTimestamp) {

    }
}
