// SPDX-License-Identifier: MIT
pragma solidity 0.8.10;

import "../../loot/IMSpaceLootCrateToken.sol";

contract Mission1LootCrate is IMSpaceLootCrateToken {

    /**
     * @dev Grants `DEFAULT_ADMIN_ROLE`, `MINTER_ROLE` and `PAUSER_ROLE` to the
     * account that deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    constructor(
        string memory _name,
        string memory _symbol,
        string memory _baseURI,
        uint256 _maxSales,
        uint256 _purchaseLimit,
        address _token,
        uint256 _price,
        address _recipient,
        address[] memory _tokens,
        uint256[] memory _amounts
    ) IMSpaceLootCrateToken(
        _name, _symbol,
        _maxSales, _purchaseLimit, _token, _price,
        _recipient,
        _tokens, _amounts
    ) {
        _setBaseURI(_baseURI);
    }
}
