// SPDX-License-Identifier: MIT
pragma solidity ^0.8.10;

import "../presets/IMSpaceAccessToken.sol";

contract MockIMSpaceAccessToken is IMSpaceAccessToken {

    /**
     * @dev Grants `DEFAULT_ADMIN_ROLE`, `MINTER_ROLE` and `PAUSER_ROLE` to the
     * account that deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    constructor(
        string memory name,
        string memory symbol,
        string memory baseTokenURI
    ) IMSpaceAccessToken(name, symbol, baseTokenURI) {

    }
}
